const SET_CARDS = 'SET_CARDS';
const LOAD_CARDS = 'LOAD_CARDS';
const LOAD_CARD = 'LOAD_CARD';
const LOAD_PAGE = 'LOAD_PAGE'
const SET_SELECTED_CARD = 'SET_SELECTED_CARD';
const SET_SEARCH = 'SET_SEARCH';

const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES'

export {
  SET_CARDS,
  LOAD_CARDS,
  LOAD_CARD,
  LOAD_PAGE,
  SET_SELECTED_CARD,
  SET_SEARCH,
  SET_CURRENT_PAGE,
  SET_TOTAL_PAGES
}
